config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  resources :profiles
  mount Notifications::Engine => "/notifications"
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :users
  end
  namespace :mentor do
    resources :users
    resources :messages
    resources :conversations
  end
  root 'sessions#new'
  resources :conversations do
    resources :messages
  end
  resources :profiles do
    resources :comments
  end
  namespace :mentor do
    resources :profiles
  end
  namespace :admin do
    resources :profiles
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :messages, dependent: :destroy
  validates :firstName, presence: true
  validates :lastName, presence: true
  validates :email, presence: true
  validates :bio, presence: true
  validates :expertise, presence: true
  validates :occupation, presence: true
  validates :email, uniqueness: true
  before_validation { email.downcase! }
  has_secure_password
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :ensure_admin_user!
  def ensure_admin_user!
  unless current_user and current_user.admin?
    redirect_to root_path, notice:"you are not admin, ask for help?"
  end
  end
def index  
  @profiles= Profile.all
User.find_each do |user|
    @users = User.all 
    @profiles= Profile.all 
end
@search=User.search(params[:q])
if params[:q]
@users=@search.result
end
  end
  def show
    @profiles= Profile.all 
  end
  def new
    @user = User.new
  end
  def edit
  end
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        session[:user_id]= @user.id
        format.html { redirect_to admin_users_path(@user), notice: 'User was created.' }
        format.json { render :index, status: :created, location: admin_users_path(@user) }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
  if params[:mentor]
    @user.update(mentor: params[:mentor])
      redirect_to admin_user_path(@user), notice: 'user changed'
  elsif @user.update(user_params)
        format.html { redirect_to admin_user_path(@user), notice: 'User was  updated.' }
        format.json { render :index, status: :ok, location: admin_user_path(@user) }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
    
    end
  end
  def destroy
    @user.destroy
     redirect_to admin_users_path, notice: 'User was  destroyed.'  
  end
  private
    def set_user
      @user = User.find(params[:id])
    end
    def user_params
      params.require(:user).permit(:firstName, :lastName, :email, :address, :bio, :occupation, :expertise, :admin, :mentor, :password, :password_confirmation)
    end
end

app/controllers/mentor/conversations_controller.rb
class Mentor::ConversationsController < ApplicationController
  def index
    @conversations = Conversation.all
  end
  def create
    if logged_in?
      if Conversation.between(params[:sender_id], params[:recipient_id]).present?
        @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
      else
        @conversation = Conversation.create!(conversation_params)
      end
        redirect_to conversation_messages_path(@conversation)
    else
      redirect_to root_path
    end
  end

  private

  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end
end

app/controllers/mentor/messages_controller.rb
class Mentor::MessagesController < ApplicationController
    before_action do
      @conversation = Conversation.find(params[:conversation_id])
    end
    def index
      # These are statements written in the index action
      # To make it easier to understand what you are doing in each part
      # Although it is written like this, because it is a little redundant code to use it in actual field
      # If you have the extra resources, try to refactor your code!
      @messages = @conversation.messages
      if @messages.length > 10
        @over_ten = true
        @messages = Message.where(id: @messages[-10..-1].pluck(:id))
      end
    
      if params[:m]
        @over_ten = false
        @messages = @conversation.messages
      end
    
      if @messages.last
        @messages.where.not(user_id: current_user.id).update_all(read: true)
      end
    
      @messages = @messages.order(:created_at)
      @message = @conversation.messages.build
    end
  
    def create
      @message = @conversation.messages.build(message_params)
      if @message.save
        redirect_to conversation_messages_path(@conversation)
      else
        render 'index'
      end
    end
  
    private
  
    def message_params
      params.require(:message).permit(:body, :user_id)
    end
  end

app/controllers/mentor/profiles_controller.rb
class Mentor::ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  def index
    @profiles= Profile.all
  end
  def show
    @comments = @profile.comments
    @comment = @profile.comments.build
  end
  def new
    @profile = Profile.new
  end
  def edit
  end
  def create
    @profile = Profile.new(profile_params)
    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    def set_profile
      @profile = Profile.find(params[:id])
    end
    def profile_params
      params.require(:profile).permit(:pic, :cv, :user_id)
    end
end

app/controllers/mentor/users_controller.rb
class Mentor::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all
    @profiles= Profile.all
  end
  def show
  end
  def new
    @user = User.new
  end
  def edit
  end
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        session[:user_id]= @user.id
        redirect_to mentor_users_path(@user), notice: 'User was successfully created.'
      else
        render :new
      end
    end
  end
  def update
    respond_to do |format|
      if @user.update(user_params)
        redirect_to @user, notice: 'User was successfully updated.' 
      else
        render :edit
      end
    end
  end
  def destroy
    @user.destroy
    respond_to do |format|
    redirect_to users_url, notice: 'User was successfully destroyed.' 
    end
  end
  private
    def set_user
      @user = User.find(params[:id])
    end
    def user_params
      params.require(:user).permit(:firstName, :lastName, :email, :address, :bio, :occupation, :expertise, :admin, :mentor, :password, :password_confirmation)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @profiles= Profile.all
    @users = User.all
    User.find_each do |user|
      @users = User.all.where("mentor", "%#{params[:users]} %",true)
  end
  @search=User.search(params[:q])
  if params[:q]
  @users=@search.result
  end
end
  def show
    @profiles= Profile.all
  end
  def new
    @user = User.new
  end
  def edit
  end
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id]= @user.id
        format.html { redirect_to @user, notice: 'User was complteted created.' }
        format.json { render :index, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was complteted updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was complteted destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    def set_user
      @user = User.find(params[:id])
    end
    def user_params
      params.require(:user).permit(:firstName, :lastName, :email, :address, :bio, :occupation, :expertise, :admin, :mentor, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/mentor/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstName %>
    <%= form.text_field :firstName %>
  </div>

  <div class="field">
    <%= form.label :lastName %>
    <%= form.text_field :lastName %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>

  <div class="field">
    <%= form.label :occupation %>
    <%= form.text_field :occupation %>
  </div>

  <div class="field">
    <%= form.label :expertise %>
    <%= form.text_field :expertise %>
  </div>

  <div class="field">
    <%= form.label :admin %>
    <%= form.radio_button :admin, 'Admin' %>
  </div>
  <div class="field">
    <%= form.label :mentor %>
    <%= form.radio_button :mentor, 'Mentor' %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mentor/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/mentor/users/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="#">FreeMentorship</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item active">
      <%= link_to 'Mentor',mentor_users_path,class:"nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Abot Us </a>
        </li>
        <li class="nav-item ">
        <a class="nav-link" href="#">Contact Us </a>
      </li>
        <li class="nav-item ">
        <%= link_to 'Inbox Session',mentor_conversations_path,class:"nav-link" %>
      </li>   
    </ul>
    <%= link_to current_user.lastName,mentor_user_path(current_user.id),class:'nav-link ml-auto' %>
    <%= link_to "Logout", session_path(current_user.id), method: :delete ,class:"nav-link"%>
  </div>
</nav>
<div class="container user-cards-container ">
<p id="notice"><%= notice %></p>
  <div class="row">
    <div class="col-md-6">
      <div class="card" style="width: 25rem;">
        <% @users.each do |user| %>
          <% if user.id == current_user.id %>
          <div class="card-header" style="color:blue; "><b><%= user.email %>
          <% if logged_in? %>
          <% check = 0, links='1', id=nil %>
          <% @profiles.each do |profile| %>
          <% if current_user.id == profile.user_id %>
            <% check = 1%>
            <%links = profile.pic %>
            <%id =profile%>
          <% end %>
          <% end %>
          <% if check==1 %>
          <p><%= image_tag links,size:"50x60", class:"rounded" unless links.blank? %></p>
          <% else %>
          <% end %>
          <% end %>
          </b></div>
        <div class="card-body" style="width: 25rem;">
        <h6> First Name</h6><%= user.lastName %>
        <h6> Last Name</h6><%= user.firstName %>
        <h6> Email</h6> <%= user.email %>
        <h6> Address</h6> <%= user.address %>
        <h6> Occupation</h6> <%= user.occupation %>
        <h6> Expertise</h6> <%= user.expertise %>
        <h6> Bio</h6> <%= user.bio %>
        </div>
        <div class="card-footer">
          <%= link_to 'Edit', edit_mentor_user_path(user),class:"btn btn-outline-info" %>
          <%= link_to 'Destroy', mentor_users_path , method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-outline-danger" %>
          <%= link_to 'My Session',mentor_conversations_path(sender_id: current_user.id, recipient_id: user.id), method: :post,class:"btn btn-outline-info" %>
          <% end %>
        <% end %>
        </div>
      </div>
    </div>
    
    <div class="col-md-6">
      <div class="card ml-auto" style="width: 15rem;margin-left:7px;">
        <div class="card-header"><%= link_to "Profile", user_path(current_user.id),class:"col-sm-3",class:"btn btn-secondary" %>
        <div class="card-header">View Submission Request</div>
        <div class="card-body"><% if logged_in? %>
        <% check = 0, links='1', id=nil %>
        <% @profiles.each do |profile| %>
        <% if current_user.id == profile.user_id %>
          <% check = 1%>
          <%links = profile.pic %>
          <%id =profile%>
          <strong>Cv:
        <%= link_to 'view' ,profile.cv%>
        <%= link_to 'Download',profile.cv, download: ''%>
          </strong>
        <% end %>
        <% end %>
        <% if check==1 %>
        <p><%= image_tag links,size:"50x60", class:"rounded" unless links.blank? %></p>
        </div>
        <div class="card-footer"><%= link_to 'Edit ', edit_mentor_profile_path(id),class:"col-sm-3",class:"btn btn-secondary"%>
        <%= link_to 'remove ', id, method: :delete, data: { confirm: 'Are you sure?' },class:"col-sm-3",class:"btn btn-danger" %>
        <% else %>
        <p><i class="fal fa-user"></i></p>
        <%= link_to 'upload profile ', new_mentor_profile_path ,class:"btn btn-secondary"%>
        <% end %>
        <% end %>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>





 
 

app/views/mentor/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/mentor/users/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="#">FreeMentorship</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Mentor',mentor_users_path,class:"nav-link" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Abot Us </a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="#">Contact Us </a>
      </li>
      <li class="nav-item ">
        <%= link_to 'Inbox Session', conversations_path,class:"nav-link" %>
      </li>
    </ul>
    <%= link_to current_user.lastName,mentor_user_path(current_user.id),class:'nav-link ml-auto' %>
    <%= link_to "Logout", session_path(current_user.id), method: :delete ,class:"nav-link"%>
  </div>
</nav>

<div class="container user-cards-container ">
  <p id="notice"><%= notice %></p>
  <div class="row d-flex justify-content-center">
    <div class="col-md-6">
      <div class="card" style="width: 25rem;">
        <div class="card-header" style="color:blue; "><b><%= @user.email %></div>
        <div class="card-body" style="width: 25rem;">
          <strong>Firstname:</strong>
          <%= @user.firstName %>
          </p>
          <p>
            <strong>Lastname:</strong>
            <%= @user.lastName %>
          </p>
          <p>
            <strong>Email:</strong>
            <%= @user.email %>
          </p>
          <p>
            <strong>Address:</strong>
            <%= @user.address %>
          </p>
          <p>
            <strong>Bio:</strong>
            <%= @user.bio %>
          </p>
          <p>
            <strong>Occupation:</strong>
            <%= @user.occupation %>
          </p>
          <p>
            <strong>Expertise:</strong>
            <%= @user.expertise %>
          </p>
        </div>
        <div class="card-footer">
          <%= link_to 'Edit', edit_user_path(@user) %>
        </div>
      </div>
    </div>
   
</div>