config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  resources :profiles
  mount Notifications::Engine => "/notifications"
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :users
  end
  namespace :mentor do
    resources :users
    resources :messages
    resources :conversations
  end
  root 'sessions#new'
  resources :conversations do
    resources :messages
  end
  resources :profiles do
    resources :comments
  end
  namespace :mentor do
    resources :profiles
  end
  namespace :admin do
    resources :profiles
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :pic
  has_one_attached :cv
  has_many :comments, dependent: :destroy
end

app/controllers/admin/profiles_controller.rb
class Admin::ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  def index
    @profiles= Profile.all
  end
  def show
    @comments = @profile.comments
    @comment = @profile.comments.build
  end
  def new
    @profile = Profile.new
  end
  def edit
  end
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was  destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    def set_profile
      @profile = Profile.find(params[:id])
    end
    def profile_params
      params.require(:profile).permit(:pic, :cv, :user_id)
    end
end

app/controllers/mentor/profiles_controller.rb
class Mentor::ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  def index
    @profiles= Profile.all
  end
  def show
    @comments = @profile.comments
    @comment = @profile.comments.build
  end
  def new
    @profile = Profile.new
  end
  def edit
  end
  def create
    @profile = Profile.new(profile_params)
    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    def set_profile
      @profile = Profile.find(params[:id])
    end
    def profile_params
      params.require(:profile).permit(:pic, :cv, :user_id)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  def index
    @profiles= Profile.all
  end
  def show
    @comments = @profile.comments
    @comment = @profile.comments.build
  end
  def new
    @profile = Profile.new
  end
  def edit
  end
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was  created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was  updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was  destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    def set_profile
      @profile = Profile.find(params[:id])
    end
    def profile_params
      params.require(:profile).permit(:pic, :cv, :user_id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/admin/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :pic %>
  </div>

  <div class="field">
    <%= form.label :CV_File %>
    <%= form.file_field :cv %>
  </div>

  <div class="field">
  <% if logged_in? %>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/profiles/edit.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="#">FreeMentorship</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Home',admin_users_path,class:"nav-link" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Abot Us </a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="#">Contact Us </a>
      </li>
      <li class="nav-item ">
      <%= link_to 'Request', admin_profiles_path,class:"nav-link"%>
    </li>
    </ul>
    <%= link_to current_user.lastName,admin_user_path(current_user.id),class:'nav-link ml-auto' %>
    <%= link_to "Logout", session_path(current_user.id), method: :delete ,class:"nav-link"%>
  </div>
</nav>
<div class="container user-cards-container ">
  <p id="notice"><%= notice %></p>
  <div class="row d-flex justify-content-center">
    <div class="col-md-6">
      <div class="card" style="width: 25rem;">
        <div class="card-header" style="color:blue; "><h1>Editing Profile</h1></div>
        <div class="card-body" style="width: 25rem;">
        <%= render 'form', profile: @profile %>
        </div>
    
      </div>
    </div>
    </div>

app/views/admin/profiles/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="#">FreeMentorship</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item ">
        <%= link_to 'Admin',admin_users_path,class:"nav-link" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Abot Us </a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="#">Contact Us </a>
      </li>
    
      <li class="nav-item active">
        <%=link_to 'Request',admin_profiles_path,class:"nav-link" %>
      </li>
    </ul>
    <%= link_to current_user.lastName,admin_user_path(current_user.id),class:'nav-link ml-auto' %>
    <%= link_to "Logout", session_path(current_user.id), method: :delete ,class:"nav-link"%>
  </div>
</nav>
<div class="container user-cards-container ">
  <p id="notice"><%= notice %></p>
  <div class="card" style="width: 25rem;" >
          <% @profiles.each do |profile| %>
            <div class="card-header" ><H6>Use Email:</h6>
          <%=profile.user.email %>
            </div>
          <div class="card-body" >
          <h2> Resume Cv:
        
         <%= link_to 'Download',profile.cv, download: ''%></h2> 
          </div>
          <div class="card-body" >
          <h2>Image:
          <%= image_tag(profile.pic, style:"width:20%") %></h2>
          </div>
          <div class="card-footer">
         <%= link_to 'Comment', admin_profile_path(profile),class:"btn btn-outline-info" %>
         <%= link_to 'Edit', edit_admin_profile_path(profile),class:"btn btn-outline-info" %>
         <%= link_to 'Destroy',profile, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger" %>
</div>
<br>
<% end %>
</div>

</div>

app/views/admin/profiles/new.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="#">FreeMentorship</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Home',admin_users_path,class:"nav-link" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Abot Us </a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="#">Contact Us </a>
      </li>
      <li class="nav-item ">
      <%= link_to 'Request', admin_profiles_path,class:"nav-link"%>
    </li>
    </ul>
    <%= link_to current_user.lastName,admin_user_path(current_user.id),class:'nav-link ml-auto' %>
    <%= link_to "Logout", session_path(current_user.id), method: :delete ,class:"nav-link"%>
  </div>
</nav>
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

app/views/admin/profiles/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="#">FreeMentorship</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Admin',admin_users_path,class:"nav-link" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Abot Us </a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="#">Contact Us </a>
      </li>
      <li class="nav-item ">
      <%= link_to 'Request', admin_profiles_path,class:"nav-link"%>
    </li>
    </ul>
    <%= link_to current_user.lastName,admin_user_path(current_user.id),class:'nav-link ml-auto' %>
    <%= link_to "Logout", session_path(current_user.id), method: :delete ,class:"nav-link"%>
  </div>
</nav>
<div class="container user-cards-container ">
  <p id="notice"><%= notice %></p>
  <div class="row d-flex justify-content-center">
    <div class="col-md-6">
      <div class="card" style="width: 25rem;">
        <div class="card-header" ><b>Request submitted</b></div>
        <div class="card-body" style="width: 25rem;">
        <p>
        <div style="width:20 rem; height:auto">
          <strong>Pic:</strong>
          <%= image_tag(@profile.pic, style:"width:9%") %>
        </p>
        <p><strong>Cv:
        <%= link_to 'view' ,@profile.cv%>
        <%= link_to 'Download',@profile.cv, download: ''%>
          </strong>
        <p><%= @profile.comments.count %> comments</p>
        <p>List of Comments(Contents below are important)</p>
        <!-- Get an HTML id of this comments_area and update only the part of that div -->
        <div id="comments_area">
          <!-- Render to display the posted comment list on the profile detail page -->
          <%= render partial: 'comments/index', locals: { comments: @comments, profile: @profile } %>
        </div>
        <!-- Render to display the comment field on the blogs detail page -->
        <%= render partial: 'comments/form', locals: { comment: @comment, blog: @profile } %>
      </div>
    </div>
    </div>