config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  resources :profiles
  mount Notifications::Engine => "/notifications"
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :users
  end
  namespace :mentor do
    resources :users
    resources :messages
    resources :conversations
  end
  root 'sessions#new'
  resources :conversations do
    resources :messages
  end
  resources :profiles do
    resources :comments
  end
  namespace :mentor do
    resources :profiles
  end
  namespace :admin do
    resources :profiles
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :messages, dependent: :destroy
  validates :firstName, presence: true
  validates :lastName, presence: true
  validates :email, presence: true
  validates :bio, presence: true
  validates :expertise, presence: true
  validates :occupation, presence: true
  validates :email, uniqueness: true
  before_validation { email.downcase! }
  has_secure_password
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :ensure_admin_user!
  def ensure_admin_user!
  unless current_user and current_user.admin?
    redirect_to root_path, notice:"you are not admin, ask for help?"
  end
  end
def index  
  @profiles= Profile.all
User.find_each do |user|
    @users = User.all 
    @profiles= Profile.all 
end
@search=User.search(params[:q])
if params[:q]
@users=@search.result
end
  end
  def show
    @profiles= Profile.all 
  end
  def new
    @user = User.new
  end
  def edit
  end
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        session[:user_id]= @user.id
        format.html { redirect_to admin_users_path(@user), notice: 'User was created.' }
        format.json { render :index, status: :created, location: admin_users_path(@user) }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
  if params[:mentor]
    @user.update(mentor: params[:mentor])
      redirect_to admin_user_path(@user), notice: 'user changed'
  elsif @user.update(user_params)
        format.html { redirect_to admin_user_path(@user), notice: 'User was  updated.' }
        format.json { render :index, status: :ok, location: admin_user_path(@user) }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
    
    end
  end
  def destroy
    @user.destroy
     redirect_to admin_users_path, notice: 'User was  destroyed.'  
  end
  private
    def set_user
      @user = User.find(params[:id])
    end
    def user_params
      params.require(:user).permit(:firstName, :lastName, :email, :address, :bio, :occupation, :expertise, :admin, :mentor, :password, :password_confirmation)
    end
end

app/controllers/mentor/users_controller.rb
class Mentor::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all
    @profiles= Profile.all
  end
  def show
  end
  def new
    @user = User.new
  end
  def edit
  end
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        session[:user_id]= @user.id
        redirect_to mentor_users_path(@user), notice: 'User was successfully created.'
      else
        render :new
      end
    end
  end
  def update
    respond_to do |format|
      if @user.update(user_params)
        redirect_to @user, notice: 'User was successfully updated.' 
      else
        render :edit
      end
    end
  end
  def destroy
    @user.destroy
    respond_to do |format|
    redirect_to users_url, notice: 'User was successfully destroyed.' 
    end
  end
  private
    def set_user
      @user = User.find(params[:id])
    end
    def user_params
      params.require(:user).permit(:firstName, :lastName, :email, :address, :bio, :occupation, :expertise, :admin, :mentor, :password, :password_confirmation)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @profiles= Profile.all
    @users = User.all
    User.find_each do |user|
      @users = User.all.where("mentor", "%#{params[:users]} %",true)
  end
  @search=User.search(params[:q])
  if params[:q]
  @users=@search.result
  end
end
  def show
    @profiles= Profile.all
  end
  def new
    @user = User.new
  end
  def edit
  end
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id]= @user.id
        format.html { redirect_to @user, notice: 'User was complteted created.' }
        format.json { render :index, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was complteted updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was complteted destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    def set_user
      @user = User.find(params[:id])
    end
    def user_params
      params.require(:user).permit(:firstName, :lastName, :email, :address, :bio, :occupation, :expertise, :admin, :mentor, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="#">Free Mentorship</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Abot Us </a>
      </li>
      <li class="nav-item ">
      <a class="nav-link" href="#">Contact Us </a>
    </li>
      <li class="nav-item active">
      <a class="nav-link" href="#">Sign Up</a>
    </li>
      <li class="nav-item ">
        <a class="nav-link" href="#">Log In</a>
      </li>
    </ul>
  </div>
</nav>
<%= form_with(model: user, local: true) do |form| %>
     <% if user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
    
          <ul>
          <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field1">
          <%= form.label :admin %>
          <%= form.radio_button :admin, 'Admin' %>
        </div>
        <div class="field1">
          <%= form.label :mentor %>
          <%= form.radio_button :mentor, 'Mentor' %>
        </div>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container register-form">
            <div class="form">
                <div class="note">
                    <p>Free Mentorship Registration </p>
                </div>

                <div class="form-content">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                
                            <%= form.label :firstName, class: "label" %>
                                <%= form.text_field :firstName,class:"form-control", placeholder:"First Name " %>
                            </div>
                            
                        <div class="form-group">
                        <%= form.label :lastName, class: "label" %>
                        <%= form.text_field :lastName,class:"form-control", placeholder:"Last Name " %>
                    </div>
                    <div class="form-group">
                    <%= form.label :occupation, class: "label" %>
                    <%= form.text_field :occupation,class:"form-control", placeholder:"Occupation " %>
                </div>
                <div class="form-group">
                <%= form.label :expertise, class: "label" %>
                <%= form.text_field :expertise,class:"form-control", placeholder:"Expertise " %>
              </div>
                        </div>
                        <div class="col-md-6">
                        <div class="form-group">
                        <%= form.label :email %>
                        <%= form.text_field :email,class:"form-control", placeholder:"Email " %>
                    </div>
                    <div class="form-group">
                    <%= form.label :address, class: "label" %>
                    <%= form.text_field :address,class:"form-control", placeholder:"Address " %>
                </div>
                <div class="form-group">
                <%= form.label :bio, class: "label" %>
                <%= form.text_area :bio,class:"form-control", placeholder:"bio" %>
            </div>
                   <div class="form-group">
                   <%= form.label :password, class: "label" %>
                   <%= form.password_field :password, class:"form-control", placeholder:"Your Password "%>
                            </div>
                            <div class="form-group">
                            <%= form.label :password_confirmation, class: "label" %>
                            <%= form.password_field :password_confirmation , class:"form-control", placeholder:"Confirm Password " %>
                            </div>
                        </div>
                    </div>
                    <%= form.submit  class:"btnSubmit" %>
                    </button>
                    <p>Do you have an account?<br><%= link_to "log in", new_session_path,class:"btn btn-primary btn-sm" %>
                </div>
            </div>
        </div>
        <% end %>
        <div class="navbar navbar-expand-lg navbar-light bg-dark d-flex justify-content-center align-items-center mt-5">
        <p class="text-light">byakozwe na @Adali</p>
        </div>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<%= render 'form', user: @user %>
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="#">FreeMentorship</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item active">
      <%= link_to 'Mentor',users_path,class:"nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Abot Us </a>
        </li>
        <li class="nav-item ">
        <a class="nav-link" href="#">Contact Us </a>
      </li>
        <li class="nav-item ">
        <%= link_to 'Inbox Session', conversations_path,class:"nav-link" %>
      </li>     
    </ul>
    <form class="form-inline my-2 my-lg-0 mr-auto">
    <%= search_form_for @search do |form| %>
      <%= form.text_field :firstName_or_expertise_cont, class:"form-control mr-sm-2",placeholder:"Search"%>
      <div class="actions1"><%= form.submit "search",class:"btn btn-outline-success my-2 my-sm-0", type:"submit" %></div>
    <%end%>
    </form>
    <%= link_to current_user.lastName,user_path(current_user.id),class:'nav-link' %>
    <%= link_to "Logout", session_path(current_user.id), method: :delete ,class:"nav-link"%>
  </div>
</nav>
<div class="container cards-container ">
<p id="notice"><%= notice %></p>
  <div class="row row-cols-1 row-cols-md-3 all-card">
  <% @users.each do |user| %>
    <div class="col-md-6 mb-3 d-flex justify-content-center">  
      <div class="card "  style="width:18rem;" >       
        <% if user.id != current_user.id %>
        <h2 class="card-header ><%= link_to user.firstName%></h2>
        <div class="card-body">
          <h6> Last Name</h6><%= user.lastName %>
          <h6> Email</h6> <%= user.email %>
          <h6> Expertise</h6> <%= user.expertise %>
        </div>
        <div class="card-footer" >
        <%= link_to user.firstName, user,class:"btn btn-outline-info" %>
          <%= link_to 'Send Session', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: :post,class:"btn btn-outline-info" %>
          </div>
        <br/>
        <% end %>        
      </div>    
    </div>
    <% end %>
  </div>
</div>


  

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="#">FreeMentorship</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Home',users_path,class:"nav-link" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Abot Us </a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="#">Contact Us </a>
      </li>
      <li class="nav-item ">
        <%= link_to 'Inbox Session', conversations_path,class:"nav-link" %>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="#">Mentor</a>
      </li>
    </ul>
    <%= link_to current_user.lastName,user_path(current_user.id),class:'nav-link ml-auto' %>
    <%= link_to "Logout", session_path(current_user.id), method: :delete ,class:"nav-link"%>
  </div>
</nav>

<div class="container user-cards-container ">
  <p id="notice"><%= notice %></p>
  <div class="row d-flex justify-content-center">
    <div class="col-md-6">
      <div class="card" style="width: 25rem;">
        <div class="card-header" style="color:blue; "><b><%= @user.email %></div>
        <div class="card-body" style="width: 25rem;">
          <strong>Firstname:</strong>
          <%= @user.firstName %>
          </p>
          <p>
            <strong>Lastname:</strong>
            <%= @user.lastName %>
          </p>
          <p>
            <strong>Email:</strong>
            <%= @user.email %>
          </p>
          <p>
            <strong>Address:</strong>
            <%= @user.address %>
          </p>
          <p>
            <strong>Bio:</strong>
            <%= @user.bio %>
          </p>
          <p>
            <strong>Occupation:</strong>
            <%= @user.occupation %>
          </p>
          <p>
            <strong>Expertise:</strong>
            <%= @user.expertise %>
          </p>
        </div>
        <div class="card-footer">
          <%= link_to 'Edit', edit_user_path(@user) %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card ml-auto" style="width: 15rem;">
        <div class="card-header">
          <%= link_to current_user.lastName, user_path(current_user.id),class:"col-sm-3",class:"btn btn-secondary" %>
          <div class="card-header">View My Cv</div>
          <div class="card-body"><% if logged_in? %>
            <% check = 0, links='1', id=nil %>
            <% @profiles.each do |profile| %>
              <% if logged_in?%>
            <% if current_user.id == profile.user_id %>
            <% check = 1%>
            <%links = profile.pic %>
            <%id =profile%>
            <strong>Cv:
              <%= link_to 'view' ,profile.cv%>
              <%= link_to 'Download',profile.cv, download: ''%>
            </strong>
            <td><%= link_to 'comment',profile%></td>
            <% end %>
            <% end %>
            <% end %>
            <% if check==1 %>
            <p><%= image_tag links,size:"50x60", class:"rounded" unless links.blank? %></p>
          </div>
          
          <div class="card-footer">
            <%= link_to 'Edit ', edit_profile_path(id),class:"col-sm-3",class:"btn btn-secondary"%>
            <%= link_to 'remove ', id, method: :delete, data: { confirm: 'Are you sure?' },class:"col-sm-3",class:"btn btn-danger" %>
            
            <% else %>
            <p><i class="fal fa-user"></i></p>
            <%= link_to 'upload profile ', new_profile_path ,class:"btn btn-secondary"%>
            <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>     
  </div>
</div>